### Post Adtouch to generate 1
POST http://localhost:8080/v1/adtouch
Content-Type: application/json

{
  "trackerId": "ABC",
  "createdAt": "1738654923"
}

### Post FirstOpen 1
POST http://localhost:8080/v1/event
Content-Type: application/json

{
  "adId": "aksgnsdkjlnbkldngksfdnk",
  "eventType": "FirstOpen",
  "adKey": "808080808"
}

### Post "Privet!"
POST http://localhost:8080/
Content-Type: application/json

{
  "text": "Privet!"
}

### Get all the messages
GET http://localhost:8080/

### Get the message by its id
@id=1e96047b-de55-4561-88c1-9cbec43fa0f4
GET http://localhost:8080/{{id}}
