### Post Adtouch 1
// @no-log
POST http://localhost:8080/v1/adtouch
Content-Type: application/json

{
  "trackerId": "ABC",
  "createdAt": "{{$timestamp}}"
}

### Post Adtouch 2
// @no-log
POST http://localhost:8080/v1/adtouch
Content-Type: application/json

{
  "trackerid": "ABC",
  "createdat": "{{$timestamp}}"
}

### Post Adtouch 3
POST http://localhost:8080/v1/adtouch
Content-Type: application/json

{
  "trackerId": "123",
  "createdAt": "{{$timestamp*1000}}",
  "poop": "poop"
}


### Post FirstOpen 1
POST http://localhost:8080/v1/event
Content-Type: application/json

{
  "adId": "{{$uuid}}",
  "eventType": "FirstOpen",
  "adKey": "d84d1417b"
}

### Post FirstOpen 2
POST http://localhost:8080/v1/event
Content-Type: application/json

{
  "adId": "{{$uuid}}",
  "eventType": "FirstOpen"
}


### Post Purchase 1
POST http://localhost:8080/v1/event
Content-Type: application/json

{
  "adId": "8bb5470f-2ace-4b72-a9fb-870c25b2228e",
  "eventType": "Purchase",
  "items": [
    {
      "productId": "123",
      "productName": "1",
      "productPrice": "100"
    },
    {
      "productId": "124",
      "productName": "2",
      "productPrice": "200"
    }
  ]
}

### Post Purchase 2
POST http://localhost:8080/v1/event
Content-Type: application/json

{
  "adId": "8bb5470f-2ace-4b72-a9fb-870c25b2228e",
  "eventType": "Purchase",
  "items": [
    {
      "productId": "123",
      "productName": "1",
      "productPrice": "100"
    },
    {
      "productId": "124",
      "productName": "2",
      "productPrice": "200"
    }
  ]
}
